### ISSUE TITLE
setDefaultValue ignored on short option with OPTIONAL_ARGUMENT

### ISSUE THREAD

**Issue by kwhat** [getopt-php/getopt-php#109] opened 2017-12-16 23:10 UTC
Hi,

There appears to be a small problem with optional arguments and default values.

    Option::create('v', "verbose", GetOpt::OPTIONAL_ARGUMENT)
        ->setDescription("Set the verbosity of the job manager")
        ->setValidation('is_numeric')
        ->setDefaultValue(6)`

If I specify `-v` the default value is 1.  If I specify `--verbose` I get "6" as loosely expected.  If I specify `-v4`, I get the same result as `--verbose`.

**Comment by tflori** [comment] 2017-12-17 13:21
@kwhat I tried to reproduce this with the following test.

```php
<?php
$getOpt = new GetOpt();
$getOpt->addOption(Option::create('v', "verbose", GetOpt::OPTIONAL_ARGUMENT)
    ->setDefaultValue(6));

$getOpt->process('-v4');

var_dump($getOpt->getOption('verbose') === '4'); // true
```

Which version are you using, or where is my error?

**Comment by kwhat** [comment] 2017-12-27 04:17
"ulrichsg/getopt-php": "^3.0"  I am going to come back to this bug.  I have another one :/

**Comment by tflori** [comment] 2017-12-27 14:32
I can't reproduce the problem. What data do you pass to the process method?

**Comment by tflori** [comment] 2018-01-16 13:24
@kwhat could you solve your issue? or is there still a problem? if yes: could you please provide a code snippet to reproduce this error?

**Comment by tflori** [comment] 2018-01-26 06:58
@kwhat I'm closing this issue because I got no answer and cant reproduce the problem. If you have a code snippet that reproduces this error feel free to reopen this issue.

**Closed by tflori** 2018-01-26 06:58 UTC
Labels: bug
