### ISSUE TITLE
Operand validation

### ISSUE THREAD

**Issue by sagikazarmark** [getopt-php/getopt-php#40] opened 2014-11-22 16:36 UTC
It is quite common that an operand is required in a cli application. Is it possible to provide operand validation as well?

I mean: check for having the required count of operands and optionally define them with names so operands can be retrieved by name and not number.

**Comment by tflori** [comment] 2017-07-03 05:13
that's a valid point for sure. I plan it for version 3

**Comment by tflori** [comment] 2017-07-11 08:51
This is a duplicate of #27 and will be closed.

**Closed by tflori** 2017-07-11 08:51 UTC
Labels: feature request
