### ISSUE TITLE
Multiple passes through GetOpt::process() yields strange results

### ISSUE THREAD

**Issue by routinet** [getopt-php/getopt-php#142] opened 2019-06-10 05:54 UTC
My app can read an INI-style text file for default settings, as well as parsing command line parameters through GetOpt.  The order of precedence I want is "default value"->"INI value"->"CL value".  However, the option for which config file to parse is a command line parameter only.  In trying to reconcile this logic, I configure GetOpt with all the commands and options, call `GetOpt->process()` to populate the values, then read the "config-file" option.  I pass that value to a routine which reads the INI and sets the value with `GetOpt->getOption($key, TRUE)->setValue($value)`.  This works fine, but leaves the INI values in charge.  To reinstate the command line parameters, I call `GetOpt->process()` again.

I've found that with a command with an operand, the second call to `process()` assigns the name of the command as the operand's value.  For example, on the initial call to `process()`, I have this command object:

```
    DisqusImporter\Commands\CreateTablesCommand::__set_state(array(
       'config' => NULL,
       'log' => NULL,
       'name' => 'create-tables',
       'shortDescription' => 'Creates the database schema',
       'longDescription' => 'Runs the SQL necessary to create the database schema.  Requires the name of the file containing the SQL commands.',
       'handler' => 'DisqusImporter\\Commands\\CreateTablesCommand::handle',
       'options' =>
      array (
      ),
       'optionMapping' =>
      array (
      ),
       'operands' =>
      array (
        0 =>
        GetOpt\Operand::__set_state(array(
           'required' => true,
           'description' => NULL,
           'default' => NULL,
           'validation' => NULL,
           'name' => 'sqlfile',
           'multiple' => false,
           'value' => 'init.sql',
           'option' => NULL,
           'validationMessage' => NULL,
        )),
      ),
    )),
```

After reading the INI, it is the same.  After the second call to `process()`, this is the object: 

```
    DisqusImporter\Commands\CreateTablesCommand::__set_state(array(
       'config' => NULL,
       'log' => NULL,
       'name' => 'create-tables',
       'shortDescription' => 'Creates the database schema',
       'longDescription' => 'Runs the SQL necessary to create the database schema.  Requires the name of the file containing the SQL commands.',
       'handler' => 'DisqusImporter\\Commands\\CreateTablesCommand::handle',
       'options' =>
      array (
      ),
       'optionMapping' =>
      array (
      ),
       'operands' =>
      array (
        0 =>
        GetOpt\Operand::__set_state(array(
           'required' => true,
           'description' => NULL,
           'default' => NULL,
           'validation' => NULL,
           'name' => 'sqlfile',
           'multiple' => false,
           'value' => 'create-tables',
           'option' => NULL,
           'validationMessage' => NULL,
        )),
      ),
    )),
```

I believe this is a side-effect of the `array_merge()` in `GetOpt::getOperands()`, but I haven't traced down there yet.  I understand a work-around could be to just discard the original GetOpt object and instantiate a new one, but that seems clumsy.

**Comment by tflori** [comment] 2019-06-11 09:48
I'm not sure to understand how you use the GetOpt object. Can you write a short code example to reproduce the problem?

I'm not sure that this a good usage of GetOpt. It's more or less just for reading the command line arguments in a structure that you can work with. The operands and options of a command are just added to the GetOpt object when the command is recognized. Because the operand is added to GetOpt (not a clone) it is then filled also in the command. The necessary change would be to clone the options and operands before adding them here: https://github.com/getopt-php/getopt-php/blob/master/src/GetOpt.php#L168

**Comment by routinet** [comment] 2019-06-12 15:32
I will try to create a simple-case scenario.  In the meantime, you can see this current project at https://github.com/routinet/data-warehousing-utils/tree/composer/disqus-mirror.  It is pretty basic.  The problem area can be found in Config::configGetOpt().  The current state has the second `process()` commented, which means my config.ini values will override the command line for now.

**Comment by routinet** [comment] 2019-06-12 20:52
Here's a real quick PoC for this issue.

```<?php
use GetOpt\GetOpt;
use GetOpt\Command;
use GetOpt\Operand;

require_once 'vendor/autoload.php';

function handler() {

}

$getopt = new GetOpt();
$operand = Operand::create('op1', Operand::REQUIRED);
$myCmd = Command::create('test', 'handler')
  ->addOperand($operand);

$getopt->addCommand($myCmd);

$getopt->process();

$cmd = $getopt->getCommand();
echo "cmd after first process:\n".var_export($cmd,1)."\n\n";

$getopt->process();
$cmd2 = $getopt->getCommand();
echo "cmd after second process:\n".var_export($cmd2,1)."\n\n";
```

**Comment by tflori** [comment] 2019-06-12 21:04
Overcomplicated and confusing code. But that's obviously not my problem.

https://github.com/routinet/data-warehousing-utils/blob/806a82161aeb8314626727624d54683a3b381e15/disqus-mirror/src/Config.php#L266

Here you should set the default value not the value not the value. But I'm sure this will not solve your problem.

What you need to do is to reset the command. The first operand is used as command but at the time the second call to process is made there is already a command and the operands and options of this command is already applied.

Think about this solution: ... Let me change to my desktop

**Comment by tflori** [comment] 2019-06-12 21:20
If you are still confused about what happens in your version have a look here:

https://github.com/getopt-php/getopt-php/blob/master/src/GetOpt.php#L168

This closure sets the command in the getopt object and adds the options and operand from the command to the getopt object. 

https://github.com/getopt-php/getopt-php/blob/master/src/Arguments.php#L50

Here we check if we don't have operands but we already have the operand from the create-table command. So we are not again setting the command: now we set an operand - and that's the operand from the command.

**Comment by tflori** [comment] 2019-06-12 21:32
to sum it up: you wan't to abstract the creation of the getopt object and now you only want to create one getopt for a thing where you need two. it will be clearer for development when you just create the commands where you need them. instead of a config file. see the example http://getopt-php.github.io/getopt-php/example.html

```php
$getOpt = new GetOpt();
$getOpt->addCommand(new CreateTableCommand);
```

And to make it clear: you need a second getOpt to read the config file parameter. If you find a hack that's fine but it's neither a bug nor a feature that I would expect to be solved from the library.

Sure an easy solution for the library would be to clone the getopt object when the process is called and return the clone with the processed data. The thing is: it's doubled memory consumption for every usage where only one developer needs it and can do it by his own. `$g2 = clone $getOpt; $g2->process(); $configFile = $g2->getOption('config-file'); unset($g2)`

**Comment by routinet** [comment] 2019-06-13 05:09
The goal of my code is to abstract the creation.  Instead of writing code to generate new commands/operands/options, our developers will be able to add new commands with a simple JSON entry, and single method implementation.  That part isn't really relevant to this issue.  The JSON file only configures the structures available, and it works fine.

In our scenario, some of our applications require parameters which should not appear on the command line (e.g., database passwords, api keys).  We use an INI-style config file to address this.  The need to merge those INI settings and command line parameters is what brought me to this issue.

Aside from my particular needs, the [PoC example](https://github.com/getopt-php/getopt-php/issues/142#issuecomment-501450838) demonstrates the problem.  Calling `process()` more than once will corrupt the value of operands for a command.  I think this could be resolved in `Arguments.php` by implementing some sanity checks on whether or not `$command` matches the current `$arg`, and probably a strategy to detect "first pass" vs "re-process".  Alternatively, a way to reset the instance to a pre-process state, but that seems unnecessarily destructive.

I'll try setting the INI-supplied values as defaults and let you know if that helps.  I'd rather not create another instance/clone if I don't have to.

**Comment by routinet** [comment] 2019-06-13 18:43
Having my INI function set the default value for options works as intended, so that is a valid work-around for my project.

**Comment by tflori** [comment] 2019-06-22 08:04
From my point of view the preferred solution (to read one option from the command line before handling the whole command line) is to create a separate getOpt object.

Closing this now as it is resolved.

**Closed by tflori** 2019-06-22 08:04 UTC
